#mq
spring:
  activemq:
  broker-url: tcp://127.0.0.1:61616
  user: admin
  password: admin

user.queue: user.queue
shop.queue: shop.queue

server:
  port: 8089




mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #mybatis.mapper-locations = classpath:mapper/**/**/*Mapper.xml

    #mybatis.typeAliasesPackage=libofei.entity.**
    #mybatis.type-aliases-package=libofei.entity.**
    #mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: libofei.entity.**
#此配置已在xml配置，以上配置是mybatis配置
#logging:
#  level:
#    root: DEBUG
#    org.mybatis: DEBUG